# Generated by Django 4.0.6 on 2022-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('stock_id', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('current_price', models.FloatField()),
                ('stock_performance_graph', models.ImageField(upload_to='')),
                ('predicted_price_1d', models.FloatField()),
                ('predicted_price_1w', models.FloatField()),
                ('predicted_price_1m', models.FloatField()),
                ('predicted_price_3m', models.FloatField()),
                ('historical_accuracy', models.FloatField()),
            ],
        ),
    ]
