# Generated by Django 4.0.6 on 2022-07-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_performance_graph',
        ),
    ]
