# Generated by Django 4.0.6 on 2022-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(default=1, verbose_name=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.IntegerField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='AAPL', max_length=200),
            preserve_default=False,
        ),
    ]
