# Generated by Django 4.0.6 on 2022-07-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_stock_id_stock_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stock_name',
        ),
    ]
