# Generated by Django 4.0.6 on 2022-07-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_stock_performance_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='historical_accuracy',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='predicted_price_1d',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='predicted_price_1m',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='predicted_price_1w',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='predicted_price_3m',
        ),
    ]
