# Generated by Django 4.0.6 on 2022-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_name_stock_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='predicted_price_1d',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='predicted_price_1m',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='predicted_price_1w',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='predicted_price_3m',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
