# Generated by Django 4.0.6 on 2022-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_predicted_price_1d_stock_predicted_price_1m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dummy',
            field=models.IntegerField(default=0),
        ),
    ]
