# Generated by Django 4.0.6 on 2022-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_stock_id_alter_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tweet_ids',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
